// This is a temporary file to hold translated content for bluetooth_service.dart
// The translations will be applied to the original file

// Key translations needed:
// Line 77: // 使用目标 Service UUID 过滤 -> // Filter using target Service UUID
// Line 79: print('🔍 开始扫描... -> print('🔍 Starting scan...
// Line 95: // 过滤设备名称：精确匹配或前缀匹配 -> // Filter device names: exact match or prefix match
// Line 100: print('⏭️  跳过设备... -> print('⏭️  Skip device...
// Line 104: print('✅ 找到目标设备... -> print('✅ Found target device...
// Line 125: print('⏹️  扫描结束... -> print('⏹️  Scan completed...
// And many more throughout the file
